
import os

LIVE_TRADING = False
DEBUG_MODE = True

STARTING_BALANCE = 1000.0
POSITION_SIZE = 0.10
MIN_NOTIONAL_USD = 10.0

STOP_LOSS_PCT = 0.03
BREAK_EVEN_TRIGGER_PCT = 0.02
TRAILING_ACTIVATE_PCT = 0.025
TRAILING_STOP_PCT = 0.012

MAX_DAILY_LOSS_PCT = 0.03
MAX_CONSECUTIVE_LOSSES = 3
COOLDOWN_MINUTES = 45
SYMBOL_COOLDOWN_MINUTES = 5
SCAN_INTERVAL_SECONDS = 5

MIN_EXPECTED_PROFIT_PCT = 0.03

MIN_SCORE_TO_BUY =7
REQUIRE_ALL_TIMEFRAMES_BULLISH = False
CANDLES_PER_TIMEFRAME = 60

ADAPTIVE_LOOKBACK_TRADES = 12
ADAPTIVE_MIN_SCORE_STEP = 2
ADAPTIVE_MIN_SCORE_FLOOR = 20
ADAPTIVE_MIN_SCORE_CAP = 32
ADAPTIVE_POSITION_UPSHIFT = 1.15
ADAPTIVE_POSITION_DOWNSHIFT = 0.75
ADAPTIVE_MAX_POSITION_SIZE = 0.15
ADAPTIVE_MIN_POSITION_SIZE = 0.05
UNDERPERFORM_SYMBOL_LOOKBACK = 20
UNDERPERFORM_SYMBOL_MIN_TRADES = 3
UNDERPERFORM_SYMBOL_MAX_WINRATE = 0.35
UNDERPERFORM_SYMBOL_PENALTY = 3

LAST_TRADED_SYMBOL_PENALTY = 0
RECENT_SYMBOL_PENALTY = 0
RECENT_SYMBOL_MEMORY = 5

MAX_OPEN_POSITIONS = 5
MAX_TRADES_PER_SYMBOL = 1
TOP_GAINERS_ENABLED = True
TOP_GAINERS_LIMIT = 15
TOP_GAINERS_REFRESH_SECONDS = 300
TOP_GAINERS_MIN_24H_VOLUME_USD = 250000.0
TOP_GAINERS_MIN_PRICE_CHANGE_PCT = 0.0

WATCHLIST = [
    "BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "DOGE-USD",
    "ADA-USD", "AVAX-USD", "LINK-USD", "ALGO-USD", "LTC-USD", "DOT-USD",
    "BCH-USD", "UNI-USD", "ATOM-USD", "AAVE-USD", "FIL-USD",
    "ETC-USD", "NEAR-USD", "APT-USD", "ARB-USD"
]

TIMEFRAMES = {
    "5m": 300,
    "15m": 900,
    "1h": 3600,
}

STATE_FILE = "pro_state.json"
TRADE_CSV = "trade_history.csv"
EVENT_LOG = "bot_events.log"
LOCK_FILE = "bot.lock"

DISCORD_ENABLED = True
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "")
DISCORD_SUMMARY_INTERVAL = 3600
